"""Add rating and reading_status to books

Revision ID: add_rating_and_status
Revises: 437e422d5556
Create Date: 2025-11-10 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_rating_and_status'
down_revision = '437e422d5556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('reading_status', sa.String(length=50), nullable=True, server_default='want_to_read'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('reading_status')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
